name: package
on: 
  workflow_dispatch:
jobs:
  package_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: '22'
        cache: npm
    - run: npm ci
    - run: npm run package -- linux
    - uses: actions/upload-artifact@v6
      with:
        name: linux
        path: |
          dist/*.deb
          dist/*.rpm
          dist/*.zip
  package_macos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: '22'
        cache: npm
    - run: npm ci
    - run: npm run package -- darwin --arch=universal
    - uses: actions/upload-artifact@v6
      with:
        name: macos
        path: |
          dist/*.dmg
          dist/*.zip
  package_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: '22'
        cache: npm
    - run: npm ci
    - run: npm run package -- win32
    - uses: actions/upload-artifact@v6
      with:
        name: windows
        path: |
          dist/*.exe
          dist/*.nupkg
          dist/*.zip
